### PR TITLE
Fix(SDK): Use Unity's native Color type, add init checks

### LINKED ISSUE #9: .color in GetProfile() should return Color typed instance too

### LINKED ISSUE #12: methods called before insertCoin callback should error out
I shouldn't be allowed to do:

```csharp
PlayroomKit.InsertCoin(() => {})
PlayroomKit.SetState(...)
```

All methods that are called before playroom has initialized should fail.

### LINKED ISSUE #15: Mock Mode: Dont create new player on each .MyPlayer() call
https://github.com/asadm/playroom-unity/blob/c0c11be750c9ef1d988cf4b1d7f5fae765354825/Assets/PlayroomKit/PlayroomKit.cs#L129C34-L129C34

Reason:
I want to be able to do this in my code:
```cs
PlayroomKit.Player myPlayer = PlayroomKit.MyPlayer();
int myIndex =playerList.IndexOf(myPlayer);
```

If the player is new each time, I cannot do this.

### PR DESCRIPTION
**Pull request by momintlh**
- UnityEngine.Color type from GetProfile.Color  >> Resolves #9 
- Updated GetPlayer in MockMode  >>  Resolves #15  
- Added checks for if InsertCoin is called in MockMode  >>  Resolves #12

### CODE REVIEW

**Review by SaadBazaz — CHANGES_REQUESTED** [review]
May need to check if other functions can be called before insertCoin. Maybe it's already implemented?

**Comment by momintlh** [comment]
> 

We have a check for that in JSLIB side for that already in each function.

**Comment by momintlh** [comment]
> What about when a function is called before InsertCoin in **non-mock mode?**
> 
> https://github.com/asadm/playroom-unity/blob/57f11c92b02558349cfe775f11954245a593c54d/Assets/PlayroomKit/PlayroomKit.cs#L97
> 
> Maybe isInitialized should be for both Mock and Non-Mock modes?
> 
> ```
> function SomeAction () {
>     
>     if (!isInitialized) Debug.Error("PlayroomKit must be initialized first. Call insertCoin.")
>     
>     if (!isRunningInBrowser()) {
>         // do some action
>     }
>     else {
>         // do some action but in mock mode
>     }
> 
> }
> ```

We have a check for that in JSLIB side already in each function.

**Comment by SaadBazaz** [comment]
> We have a check for that in JSLIB side already in each function.
> 
> ```
> if (!window.Playroom) {
>       console.error(
>         "Playroom library is not loaded. Please make sure to call InsertCoin first."
>       );
>       return;
> ```
> 
> Doing in Unity will lead to the same console.log.

Okay that's good then. But do you think some of our functions may bypass that?
https://github.com/asadm/playroom-unity/blob/c0c11be750c9ef1d988cf4b1d7f5fae765354825/Assets/PlayroomKit/PlayroomKit.cs#L104

**Comment by SaadBazaz** [comment]
Looks better to me. Tested as well. Merging.

**Pull request merged**
