### PR TITLE
Non-Upstream Functions Private

### PR DESCRIPTION
**Pull request by momintlh**
* Made all non-upstream functions private #72
* Removed unnecessary warning log in RPC.
* Removed `GetStateFloat` in Player class, because there already is `GetStateDict`

### CODE REVIEW

**Comment by SaadBazaz** [comment]
> Removed GetStateFloat in Player class, because there already is **GetStateDict**
I don't seem to understand how Float and Dict are related 😅

**Review by SaadBazaz — APPROVED** [review]
lgtm

**Review by SaadBazaz — CHANGES_REQUESTED** [review]
Here's a list of functions which I think **might** need to be private:

1. https://github.com/asadm/playroom-unity/blob/647af7bdf0b97cbcbc1a38b849c5b589f65fe7b4/Assets/PlayroomKit/PlayroomKit.cs#L288
2. https://github.com/asadm/playroom-unity/blob/647af7bdf0b97cbcbc1a38b849c5b589f65fe7b4/Assets/PlayroomKit/PlayroomKit.cs#L302
3. https://github.com/asadm/playroom-unity/blob/647af7bdf0b97cbcbc1a38b849c5b589f65fe7b4/Assets/PlayroomKit/PlayroomKit.cs#L771
4. https://github.com/asadm/playroom-unity/blob/647af7bdf0b97cbcbc1a38b849c5b589f65fe7b4/Assets/PlayroomKit/PlayroomKit.cs#L925
5. https://github.com/asadm/playroom-unity/blob/647af7bdf0b97cbcbc1a38b849c5b589f65fe7b4/Assets/PlayroomKit/PlayroomKit.cs#L1248
6. https://github.com/asadm/playroom-unity/blob/647af7bdf0b97cbcbc1a38b849c5b589f65fe7b4/Assets/PlayroomKit/PlayroomKit.cs#L1300
7. https://github.com/asadm/playroom-unity/blob/647af7bdf0b97cbcbc1a38b849c5b589f65fe7b4/Assets/PlayroomKit/PlayroomKit.cs#L1335

Can you check these out and confirm?

**Comment by momintlh** [comment]
> Here's a list of functions which I think **might** need to be private:
> 
> 1. https://github.com/asadm/playroom-unity/blob/647af7bdf0b97cbcbc1a38b849c5b589f65fe7b4/Assets/PlayroomKit/PlayroomKit.cs#L288
> 2. https://github.com/asadm/playroom-unity/blob/647af7bdf0b97cbcbc1a38b849c5b589f65fe7b4/Assets/PlayroomKit/PlayroomKit.cs#L302
> 3. https://github.com/asadm/playroom-unity/blob/647af7bdf0b97cbcbc1a38b849c5b589f65fe7b4/Assets/PlayroomKit/PlayroomKit.cs#L771
> 4. https://github.com/asadm/playroom-unity/blob/647af7bdf0b97cbcbc1a38b849c5b589f65fe7b4/Assets/PlayroomKit/PlayroomKit.cs#L925
> 5. https://github.com/asadm/playroom-unity/blob/647af7bdf0b97cbcbc1a38b849c5b589f65fe7b4/Assets/PlayroomKit/PlayroomKit.cs#L1248
> 6. https://github.com/asadm/playroom-unity/blob/647af7bdf0b97cbcbc1a38b849c5b589f65fe7b4/Assets/PlayroomKit/PlayroomKit.cs#L1300
> 7. https://github.com/asadm/playroom-unity/blob/647af7bdf0b97cbcbc1a38b849c5b589f65fe7b4/Assets/PlayroomKit/PlayroomKit.cs#L1335
> 
> Can you check these out and confirm?

`GetPlayer()` is quite useful with RPC, `GetStateDict` is for dictionaries (these are not overloaded with GetState<>), and `OnQuitWrapperCallback()` is inside the player class and it is being used inside the Playroom class so this needs to be public.

**Comment by SaadBazaz** [comment]
> `GetPlayer()` is quite useful with RPC
Okay that works.

> `GetStateDict` is for dictionaries (these are not overloaded with GetState<>)
Is there a way we can overload it somehow?

 > `OnQuitWrapperCallback()` is inside the player class and it is being used inside the Playroom class so this needs to be public.
Is there a way we can hide such functions from end-user (developers) but not from between classes? Maybe there's another access method other than private and public?

**Review by SaadBazaz — APPROVED** [review]
- [x] GetState now supports Dict
- [x] OnQuitWrapperCallback() is now private

I think we can call this one a win.

**Pull request merged**
